name: CI

on:
  push:
    branches: ["main"]

jobs:
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: flake8
        working-directory: ./python-project-50
        run: make lint

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pytest
        working-directory: ./python-project-50
        run: make pytest
