name: CI

on:
  push:
    branches: ["main"]

jobs:
  run_linter:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      name: linter
      run: make lint

  run_tests:
  runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      name: linter
      run: make pytest
