name: CI

on:
  push:
    branches: ["main"]

jobs:
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install poerty
        uses: snok/install-poetry@v1
        
      - name: install dependencies
        run: poetry install

      - name: flake8
        run: make lint

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install poerty
        uses: snok/install-poetry@v1

      - name: install dependencies
        run: poetry install

      - name: pytest
        run: make pytest
  
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: path
        run: echo $PWD
